# Generated by Django 4.2.7 on 2025-06-21 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de facture')),
                ('invoice_date', models.DateField(auto_now_add=True, verbose_name='Date de facture')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('cheque', 'Chèque'), ('transfer', 'Virement')], default='cash', max_length=10, verbose_name='Mode de paiement')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Adresse de livraison')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Date de livraison')),
                ('installation_notes', models.TextField(blank=True, verbose_name="Notes d'installation")),
                ('warranty_info', models.TextField(blank=True, verbose_name='Informations de garantie')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sous-total')),
                ('services_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total services')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remise')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant TVA')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='draft', max_length=10, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('cheque', 'Chèque'), ('transfer', 'Virement')], max_length=10, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Référence')),
                ('status', models.CharField(choices=[('completed', 'Terminé'), ('pending', 'En attente'), ('failed', 'Échoué')], default='completed', max_length=10, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('delivery', 'Livraison'), ('installation', 'Installation'), ('cutting', 'Découpe'), ('packaging', 'Emballage'), ('other', 'Autre')], max_length=15, verbose_name='Type de service')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Service de facture',
                'verbose_name_plural': 'Services de facture',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sous-total')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Largeur (cm)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Hauteur (cm)')),
                ('thickness', models.CharField(blank=True, max_length=10, verbose_name='Épaisseur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice', verbose_name='Facture')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.glassproduct', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article de facture',
                'verbose_name_plural': 'Articles de facture',
            },
        ),
    ]
