# Generated by Django 4.2.7 on 2025-06-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom/Raison sociale')),
                ('customer_type', models.CharField(choices=[('individual', 'Particulier'), ('commercial', 'Entreprise')], default='individual', max_length=12, verbose_name='Type')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('nis', models.CharField(blank=True, max_length=50, verbose_name='NIS')),
                ('rc', models.CharField(blank=True, max_length=50, verbose_name='RC')),
                ('art', models.CharField(blank=True, max_length=50, verbose_name='ART')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Personne de contact')),
                ('payment_terms', models.CharField(default='Paiement à la livraison', max_length=100, verbose_name='Conditions de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
    ]
