# Generated by Django 4.2.7 on 2025-06-20 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code produit')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('glass_type', models.CharField(choices=[('window', 'Verre de fenêtre'), ('mirror', 'Miroir'), ('shower', 'Verre de douche'), ('table', 'Plateau de table'), ('decorative', 'Verre décoratif'), ('security', 'Verre sécurisé'), ('tempered', 'Verre trempé'), ('laminated', 'Verre feuilleté')], max_length=20, verbose_name='Type de verre')),
                ('thickness', models.CharField(choices=[('3', '3mm'), ('4', '4mm'), ('5', '5mm'), ('6', '6mm'), ('8', '8mm'), ('10', '10mm'), ('12', '12mm'), ('15', '15mm'), ('19', '19mm')], max_length=3, verbose_name='Épaisseur')),
                ('color', models.CharField(choices=[('clear', 'Transparent'), ('bronze', 'Bronze'), ('grey', 'Gris'), ('green', 'Vert'), ('blue', 'Bleu'), ('black', 'Noir')], default='clear', max_length=10, verbose_name='Couleur')),
                ('finish', models.CharField(choices=[('polished', 'Poli'), ('frosted', 'Dépoli'), ('textured', 'Texturé'), ('sandblasted', 'Sablé')], default='polished', max_length=15, verbose_name='Finition')),
                ('unit', models.CharField(choices=[('sqm', 'Mètre carré'), ('piece', 'Pièce')], default='sqm', max_length=10, verbose_name='Unité de mesure')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de revient')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité en stock')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Stock minimum')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=10, verbose_name='Statut')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Produit en verre',
                'verbose_name_plural': 'Produits en verre',
                'ordering': ['name'],
            },
        ),
    ]
