# Generated by Django 4.2.7 on 2025-07-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Couleur',
                'verbose_name_plural': 'Couleurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GlassFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Finition',
                'verbose_name_plural': 'Finitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GlassThickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=3, unique=True)),
                ('display_name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Épaisseur',
                'verbose_name_plural': 'Épaisseurs',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='GlassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type de verre',
                'verbose_name_plural': 'Types de verre',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unité de mesure',
                'verbose_name_plural': 'Unités de mesure',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='glassproduct',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.glasscolor', verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='glassproduct',
            name='finish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.glassfinish', verbose_name='Finition'),
        ),
        migrations.AlterField(
            model_name='glassproduct',
            name='glass_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.glasstype', verbose_name='Type de verre'),
        ),
        migrations.AlterField(
            model_name='glassproduct',
            name='thickness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.glassthickness', verbose_name='Épaisseur'),
        ),
        migrations.AlterField(
            model_name='glassproduct',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unit', verbose_name='Unité de mesure'),
        ),
    ]
