# Generated by Django 5.2.4 on 2025-07-04 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_glasscolor_glassfinish_glassthickness_glasstype_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glassproduct',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.glasscolor', verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='glassproduct',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='glassproduct',
            name='finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.glassfinish', verbose_name='Finition'),
        ),
        migrations.AlterField(
            model_name='glassproduct',
            name='glass_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.glasstype', verbose_name='Type de verre'),
        ),
        migrations.AlterField(
            model_name='glassproduct',
            name='thickness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.glassthickness', verbose_name='Épaisseur'),
        ),
        migrations.AlterField(
            model_name='glassproduct',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unit', verbose_name='Unité de mesure'),
        ),
    ]
