# Generated by Django 4.2.7 on 2025-06-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('business_type', models.CharField(default='Commerce de verre et installation', max_length=200, verbose_name="Type d'activité")),
                ('address', models.TextField(verbose_name='Adresse')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='Fax')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('rc', models.CharField(blank=True, max_length=50, verbose_name='RC')),
                ('art', models.CharField(blank=True, max_length=50, verbose_name='ART')),
                ('nis', models.CharField(blank=True, max_length=50, verbose_name='NIS')),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name='NIF')),
                ('rib', models.CharField(blank=True, max_length=50, verbose_name='RIB')),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Capital social')),
                ('logo', models.ImageField(blank=True, upload_to='company/logos/', verbose_name='Logo')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='Taux de TVA (%)')),
                ('operating_hours', models.TextField(blank=True, verbose_name="Heures d'ouverture")),
                ('certifications', models.TextField(blank=True, verbose_name='Certifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
    ]
