# Generated by Django 4.2.7 on 2025-06-24 08:09

import apps.audit.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('PAID', 'Payé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('vendor', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur/Bénéficiaire')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de référence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Dépense additionnelle',
                'verbose_name_plural': 'Dépenses additionnelles',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('RECEIVED', 'Reçu'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Client/Source')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de référence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Revenu additionnel',
                'verbose_name_plural': 'Revenus additionnels',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PAYROLL', 'Paiements des employés'), ('EQUIPMENT', "Charges d'équipement"), ('MAINTENANCE', 'Charges de maintenance'), ('UTILITIES', 'Électricité/Eau/Gaz'), ('MATERIALS', 'Matériaux et fournitures'), ('TRANSPORT', 'Transport et livraison'), ('INSURANCE', 'Assurances'), ('TAXES', 'Taxes et impôts'), ('OTHER', 'Autres charges')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
            },
        ),
        migrations.CreateModel(
            name='RevenueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RECYCLING', 'Recyclage de verre'), ('WASTE_SALE', 'Vente de déchets'), ('EQUIPMENT_RENTAL', "Location d'équipement"), ('TRAINING', 'Formation et consultation'), ('REPAIR_SERVICE', 'Services de réparation'), ('OTHER', 'Autres revenus')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de revenu',
                'verbose_name_plural': 'Catégories de revenus',
            },
        ),
        migrations.CreateModel(
            name='RevenueDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.audit.models.revenue_upload_path, verbose_name='Fichier')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='audit.additionalrevenue')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document de revenu',
                'verbose_name_plural': 'Documents de revenus',
            },
        ),
        migrations.CreateModel(
            name='ExpenseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.audit.models.expense_upload_path, verbose_name='Fichier')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='audit.additionalexpense')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document de dépense',
                'verbose_name_plural': 'Documents de dépenses',
            },
        ),
        migrations.AddField(
            model_name='additionalrevenue',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.revenuecategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='additionalrevenue',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='additionalexpense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.expensecategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='additionalexpense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
