# Generated by Django 4.2.7 on 2025-06-23 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('export', 'Export'), ('import', 'Import')], max_length=10, verbose_name="Type d'opération")),
                ('format', models.CharField(choices=[('json', 'JSON'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10, verbose_name='Format')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=15, verbose_name='Statut')),
                ('include_customers', models.BooleanField(default=True, verbose_name='Inclure les clients')),
                ('include_products', models.BooleanField(default=True, verbose_name='Inclure les produits')),
                ('include_orders', models.BooleanField(default=True, verbose_name='Inclure les commandes')),
                ('include_invoices', models.BooleanField(default=True, verbose_name='Inclure les factures')),
                ('include_suppliers', models.BooleanField(default=True, verbose_name='Inclure les fournisseurs')),
                ('include_company', models.BooleanField(default=True, verbose_name='Inclure les infos entreprise')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('export_file', models.FileField(blank=True, upload_to='backups/exports/', verbose_name="Fichier d'export")),
                ('import_file', models.FileField(blank=True, upload_to='backups/imports/', verbose_name="Fichier d'import")),
                ('total_records', models.IntegerField(default=0, verbose_name="Total d'enregistrements")),
                ('processed_records', models.IntegerField(default=0, verbose_name='Enregistrements traités')),
                ('error_count', models.IntegerField(default=0, verbose_name="Nombre d'erreurs")),
                ('log_messages', models.TextField(blank=True, verbose_name='Messages de log')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Tâche de sauvegarde',
                'verbose_name_plural': 'Tâches de sauvegarde',
                'ordering': ['-created_at'],
            },
        ),
    ]
