# Generated by Django 4.2.7 on 2025-06-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='include_audit',
            field=models.BooleanField(default=True, verbose_name="Inclure les données d'audit"),
        ),
    ]
