# Generated by Django 4.2.7 on 2025-06-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_backupjob_include_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='compression',
            field=models.CharField(choices=[('none', 'Aucune'), ('zip', 'ZIP'), ('gzip', 'GZIP')], default='zip', max_length=10, verbose_name='Compression'),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='include_media',
            field=models.BooleanField(default=False, verbose_name='Inclure les fichiers média'),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='format',
            field=models.CharField(choices=[('json', 'JSON'), ('excel', 'Excel'), ('csv', 'CSV'), ('xml', 'XML'), ('sql', 'SQL')], max_length=10, verbose_name='Format'),
        ),
    ]
