# Generated by Django 4.2.7 on 2025-07-02 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backup', '0003_backupjob_compression_backupjob_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la sauvegarde')),
                ('backup_type', models.CharField(choices=[('full', 'Sauvegarde Complète'), ('partial', 'Sauvegarde Partielle')], default='full', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminée'), ('failed', 'Échouée')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enregistrement de Sauvegarde',
                'verbose_name_plural': 'Enregistrements de Sauvegarde',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('restored_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminée'), ('failed', 'Échouée')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('backup_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backup.backuprecord')),
                ('restored_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enregistrement de Restauration',
                'verbose_name_plural': 'Enregistrements de Restauration',
                'ordering': ['-restored_at'],
            },
        ),
        migrations.DeleteModel(
            name='BackupJob',
        ),
    ]
